# Generated by Django 4.2.3 on 2023-08-17 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0004_alter_vote_current_song'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='current_song',
        ),
    ]
